### ISSUE TITLE
Flatpak apps missing in App Chooser

### ISSUE THREAD

**Issue by louis77** [DevAlien/workspaces#19] opened 2020-09-01 18:41 UTC
I run Ubuntu 20.04 and use Flatpak for many apps.
Workspace v3.0.0 was also installed via Flatpak, but I don't see the other Flatpak apps in the App Chooser.

**Comment by Philip-Scott** [comment] 2020-09-01 19:12
Feels like a duplicate of https://github.com/DevAlien/workspaces/issues/12 :)

**Comment by DevAlien** [comment] 2020-09-02 09:26
Yes, this one should be solved in #12 closing for now

**Closed as completed by DevAlien** 2020-09-02 09:26 UTC
